### ISSUE TITLE
WebRTCStar.dial: Cannot read property 'io' of undefined

### ISSUE THREAD

**Issue by JamesHageman** [libp2p/js-libp2p-webrtc-star#219]
Hello!

I'm using the `p2p-webrtc-star` transport with the latest `js-ipfs` (`0.43.1`) in the browser, with the signalling server running at `localhost:9090`. I'm trying to connect two peers over WebRTC:

```javascript
node.swarm.connect("/dns4/localhost/tcp/9090/ws/p2p-webrtc-star/p2p/<other peer id>")
```

However, this fails with the following exception:

```
AggregateError: 
    TypeError: Cannot read property 'io' of undefined
        at ClassIsWrapper._connect (https://unpkg.com/ipfs@0.43.1/dist/index.js:176909:78)
        at ClassIsWrapper.dial (https://unpkg.com/ipfs@0.43.1/dist/index.js:176874:32)
        at TransportManager.dial (https://unpkg.com/ipfs@0.43.1/dist/index.js:165725:30)
        at DialRequest.dialAction (https://unpkg.com/ipfs@0.43.1/dist/index.js:164756:36)
        at https://unpkg.com/ipfs@0.43.1/dist/index.js:164916:29
        at async https://unpkg.com/ipfs@0.43.1/dist/index.js:162715:23
```

Which appears to come from this line in `WebRTCStar._connect`:
https://github.com/libp2p/js-libp2p-webrtc-star/blob/4ed25a5427b837b39fc2bdc5752cbd4dae0d5226/src/index.js#L107-L108

Full codepen for reference: https://codepen.io/jameshageman/pen/YzyYPNz

**Comment by vasco-santos** [comment]
Hey @JamesHageman 

Are you running the signalling server locally? We do not support dns resolution yet, so I think it would work if you put your local ip address in the multiaddr: `/ip4/127.0.0.1/tcp/...`

For more information, you can look into the `js-libp2p` or `js-ipfs` browser examples. Let me know if you could get this fixed

**Comment by jacobheun** [comment]
Closing due to inactivity, please reopen if you are still experiencing an issue.
