### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by Xendergo** [libp2p/js-libp2p-webrtc-star#409]
## Description:
When I run the signalling server and visit the address it's hosted on, I get a 500 error in the browser, and the server logs:
```
Debug: internal, implementation, error 
    ReferenceError: __dirname is not defined
    at handler (file:///usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/dist/src/index.js:34:59)
    at exports.Manager.execute (/usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
    at Object.internals.handler (/usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/node_modules/@hapi/hapi/lib/request.js:371:68)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Request._execute (/usr/local/lib/node_modules/@libp2p/webrtc-star-signalling-server/node_modules/@hapi/hapi/lib/request.js:281:9)
```
## How to reproduce:
Pull the container:
`docker pull libp2p/js-libp2p-webrtc-star`

Run the container:
`docker run -p 9090:9090 libp2p/js-libp2p-webrtc-star`

Go to `localhost:9090`

**Comment by toorop** [comment]
Note that even if the index.html cannot be displayed, the signaling process works as expected throught websocket.

**Comment by mateuszjarzewski** [comment]
Can we have this fixed? This project works nowhere, all examples how to run it fails with error 500.
